### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by ville-v** [martygrant/tmxloader#6]
I tried to compile this in Visual Studio, but there are numerous errors. Using variables that don't exist, dereferencing null pointer, etc.

**Comment by martygrant** [comment]
Hi there I done a quick pass and fixed the build errors. I perhaps didn't properly check the last pull request. The project is a little messy and outdated and needs some work, you might find the TMX file format has changed since I wrote this and there may be some issues there.

The errors are fixed in https://github.com/martygrant/tmxloader/commit/618776ec4e5522ec25fc62d83efdec1e814b4d6d.

I'd like to rewrite the project if I could find some time to do so.
